#!/usr/bin/env python
import sys
import json
from collections import defaultdict
from math import fsum, isclose


def test_probabilities_add_up(agg):
    for counter in agg.values():
        s = fsum(counter.values())
        assert isclose(s, 1.0)


def test_correct_levels(agg):
    with open('config.json') as f:
        config = json.load(f)
    report_every = config['report_every']
    for level in agg:
        assert level % report_every == 0


def main():
    agg = defaultdict(lambda: defaultdict(float))
    for line in sys.stdin:
        row = json.loads(line)
        lvl = row['l']
        dmg = row['d']
        prob = row['p']
        agg[lvl][dmg] += prob

    test_probabilities_add_up(agg)
    test_correct_levels(agg)


if __name__ == '__main__':
    main()
